# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-06-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import dkmodelfields.monthfield
import dkmodelfields.statusfield
import dkmodelfields.yearfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', dkmodelfields.monthfield.MonthField()),
            ],
        ),
        migrations.CreateModel(
            name='S',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', dkmodelfields.statusfield.StatusField('\n        =============== =========================================== ============\n        status          verbose explanation                         category\n        =============== =========================================== ============\n        first           First status                                # [init]\n        second          Second status                               # [ok]\n        third           Third status                                # [post]\n        =============== =========================================== ============\n        @end-progress-status\n    ', choices=[('first', 'First status'), ('second', 'Second status'), ('third', 'Third status')], db_index=True, default='first', max_length=15, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Y',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr', dkmodelfields.yearfield.YearField()),
            ],
        ),
    ]
